### ISSUE TITLE
Defendant birthdate is incomplete when you look at or print from Adobe Acrobat Pro

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#111]
@miabonardi Hi: Just made this weird discovery. When opening a completed Complaint form in Adobe Acrobat Pro, only the month of the defendant's birthday shows and prints. The rest seems to be hidden because it is "stacked."

![image](https://github.com/LSVermont/docassemble-RFApackage/assets/104463248/ae25e5ab-2c2d-47a1-aeed-69a4405eb906)
![image](https://github.com/LSVermont/docassemble-RFApackage/assets/104463248/a4ea85ef-4387-400a-b7b2-340fc37bab17)

It seems to behave well in the browsers. 

I don't have Adobe Reader so I cannot test that. Can you? I can email you the file.

It is worrisome that someone with Acrobat Pro would run into this problem. I could see domestic violence advocates having access to it on their work computers. Any ideas on how to avoid this?

**Comment by miabonardi** [comment]
@nonprofittechy could this be something with ThreePartsDate?

**Comment by nonprofittechy** [comment]
No. It's something in the PDF field properties itself

**Comment by miabonardi** [comment]
Yes that's right, its this question. I'll look into it more

![Screen Shot 2023-11-08 at 10 36 47 AM](https://github.com/LSVermont/docassemble-RFApackage/assets/65858862/fa607bab-a166-46b5-ac15-bd7e9caf304f)
