### ISSUE TITLE
Phone numbers: id: Gather users contact information and id: When law enforcement serves the order to the defendant

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#17]
Can we validate that they are entering numbers for a phone number?

**Comment by miabonardi** [comment]
Yes using `al_international_phone`

https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/altoolbox#international-phone-number-input-validation

**Comment by stavros-0** [comment]
I am doing this for id: Gather defendants phone as well.
