### ISSUE TITLE
id: About your home - add I don't know option

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#19]
For home is rented and home is owned collection of questions, offer an "I don't know" option. When they choose this, no answer will appear on the PDF. Apparently people sometimes don't know who owns or rents the place.

**Comment by miabonardi** [comment]
@stavros-0 

Expected appearance should be a choices list of:

Rent or own? 

- the home is rented
- the home is owned
- I don't know

In whose name? 
 
- rented or owned by ${ plaintiff } and ${ defendant }
- rented or owned by ${ plaintiff }
- rented or owned by ${ defendant }
- rented or owned by someone else
- I don't know
