### ISSUE TITLE
attachment:   name: 3 RFA-affidavit - For addresses with an apt or unit number, can we add "Apt" before the letter or number?

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#49]
![image](https://github.com/VTskier/docassemble-RFApackage/assets/104463248/4f9e8b10-da24-4f0d-8955-9d6fbdd4c087)

In this case it should be Apt. C, not just C.

**Comment by miabonardi** [comment]
@nonprofittechy Can you advise on the best way to do this

**Comment by miabonardi** [comment]
Install latest version of AL, this feature is added

**Comment by nonprofittechy** [comment]
I just installed it for you-2.24.0
