### ISSUE TITLE
Spreadsheet of VT Family Courts integrated into interview

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#52]
For use on the RFA interview and the upcoming Divorce interview, could you set up a spreadsheet or something for VT Family Courts that we can edit and it gets used in the interviews? Would also be able to then pop relevant court contact info to our next steps documents. (And hopefully down the line, it gets integrated into efiling.)

List of courts with contact info:
https://www.vermontjudiciary.org/court-locations?f%5B0%5D=court_division%3A4

This is not urgent for the RFA interview, but we could work it in when it's ready.

**Comment by miabonardi** [comment]
Excel sheet sent over

**Comment by miabonardi** [comment]
@VTskier Do you want me to add the courts to the RFA now too?
