### ISSUE TITLE
K.S. will transfer this repository to organization account

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#58]
@miabonardi Hi: Looks like I follow these instructions to transfer this RFA repository?

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by miabonardi** [comment]
Yes! Just make your @VTskier account an owner/member of the @LSVermont
