### ISSUE TITLE
Email with forms not received

### ISSUE THREAD

**Issue by VTskier** [VTskier/docassemble-RFApackage#64]
Two reviewers noted they did not receive an email with the forms when they put in their email address at the end. (I had one of them check their junk mail, too.) I bet we have to set up the emailing system for apps.vtcourtforms.org. Is it hard to set it up? Is now a good time to set that up?

**Comment by miabonardi** [comment]
@nonprofittechy this seems upstream

**Comment by nonprofittechy** [comment]
We do need to set up email, yes. Can you ask your IT department for SMTP credentials you can use for this? I can also help you setup a service like Send grid

**Comment by nonprofittechy** [comment]
Okay, I can look into it for you. It looks like you might just need to
publish a policy and set up a way to get notified when an email bounces.
